/// Flutter icons Challenge
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Challenge
///      fonts:
///       - asset: fonts/Challenge.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Challenge {
  Challenge._();

  static const _kFontFam = 'Challenge';
  static const String _kFontPkg = null;

  static const IconData challenge_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
