/// Flutter icons RankIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RankIcon
///      fonts:
///       - asset: fonts/RankIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RankIcon {
  RankIcon._();

  static const _kFontFam = 'Ranking';
  static const String _kFontPkg = null;

  static const IconData ribbon_award_with_star_shape = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
